# baseURL = 'https://rawpedia.rawtherapee.com/'
baseURL = ''
languageCode = 'en'
title = 'RawPedia'
theme = ['hugo-bootstrap-bare']
enableGitInfo = true

defaultContentLanguage = 'en'

[menus]
  [[menus.main]]
    name = 'Getting Started'
    pageRef = '/getting_started'
    weight = 1
  [[menus.main]]
    name = "Eek! That's not my JPEG!"
    url = '/editor/#eek-my-raw-photo-looks-different-than-the-camera-jpeg'
    weight = 2
  [[menus.main]]
    name = 'The Favorites Tab'
    url = '/favorites_tab'
    weight = 3
  [[menus.main]]
    name = 'New Raw Formats'
    url = '/adding_support_for_new_raw_formats'
    weight = 4

[languages.en]
  languageCode = 'en-US'
  languageName = 'English'
  timeZone = 'America/New_York'
  title = 'RawPedia'
  weight = 1
  [languages.en.pagination]
    path = 'page'
[languages.fr]
  languageCode = 'fr-FR'
  languageName = 'Français'
  timeZone = 'America/New_York'
  title = 'RawPedia'
  weight = 2
  [languages.fr.pagination]
    path = 'page'
# [languages.de]
#   languageCode = 'de'
#   languageName = 'Deutsch'
#   timeZone = 'America/New_York'
#   title = 'RawPedia'
#   weight = 3
#   [languages.de.pagination]
#     path = 'page'
# [languages.ca]
#   languageCode = 'ca'
#   languageName = 'Català'
#   timeZone = 'America/New_York'
#   title = 'RawPedia'
#   weight = 4
#   [languages.ca.pagination]
#     path = 'page'
# [languages.es]
#   languageCode = 'es'
#   languageName = 'Español'
#   timeZone = 'America/New_York'
#   title = 'RawPedia'
#   weight = 5
#   [languages.es.pagination]
#     path = 'page'
# [languages.it]
#   languageCode = 'it'
#   languageName = 'Italiano'
#   timeZone = 'America/New_York'
#   title = 'RawPedia'
#   weight = 6
#   [languages.it.pagination]
#     path = 'page'

[markup]
  [markup.highlight]
    # style =  'algol_nu'
    style =  'catppuccin-latte'
    # style =  'friendly'
    # style =  'monokailight'
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2
  [markup.goldmark.parser.attribute]
    block = true
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
  [markup.goldmark.renderHooks.link]
    useEmbedded = 'always'
  [markup.goldmark.renderHooks.image]
    useEmbedded = 'always'

[outputs]
  home = ['html', 'rss', 'json']
  section = ['html']
  page = ['html']
  rss = ['rss']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'assets/images'
    target = 'assets'
