baseURL = 'https://rawpedia.rawtherapee.com/'
languageCode = 'en-us'
title = 'RawPedia'
theme = ['hugo-bootstrap-bare']
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    timeZone = 'America/New_York'
    title = 'RawPedia'
    weight = 1
    [languages.en.pagination]
      path = 'page'
  [languages.fr]
    languageCode = 'fr'
    languageName = 'Français'
    timeZone = 'America/New_York'
    title = 'RawPedia'
    weight = 1
    [languages.fr.pagination]
      path = 'page'
  [languages.de]
    languageCode = 'de'
    languageName = 'Deutsch'
    timeZone = 'America/New_York'
    title = 'RawPedia'
    weight = 1
    [languages.de.pagination]
      path = 'page'
  [languages.ca]
    languageCode = 'ca'
    languageName = 'Català'
    timeZone = 'America/New_York'
    title = 'RawPedia'
    weight = 1
    [languages.ca.pagination]
      path = 'page'
  [languages.es]
    languageCode = 'es'
    languageName = 'Español'
    timeZone = 'America/New_York'
    title = 'RawPedia'
    weight = 1
    [languages.es.pagination]
      path = 'page'
  [languages.it]
    languageCode = 'it'
    languageName = 'Italiano'
    timeZone = 'America/New_York'
    title = 'RawPedia'
    weight = 1
    [languages.it.pagination]
      path = 'page'

[markup]
  [markup.highlight]
    style =  'algol_nu'
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
  [markup.goldmark.renderHooks]
    [markup.goldmark.renderHooks.link]
      useEmbedded = 'auto'
[outputs]
  home = ['html', 'rss', 'json']
  section = ['html']
  page = ['html']
  rss = ['rss']
